#ifndef __TARGET_HPP__
#define __TARGET_HPP__

#define MOTOR_LEFT_TIM_HANDLE (htim2)
#define MOTOR_RIGHT_TIM_HANDLE (htim1)

#define MOTORS_TIM_COUNTER_PERIOD 1000

#define MOTOR_BACKWARD_TIMER_CHANNEL TIM_CHANNEL_2
#define MOTOR_FORWARD_TIMER_CHANNEL TIM_CHANNEL_1

#define MAX_MOTORS_SPEED 100
#define MIN_MOTORS_SPEED -MAX_MOTORS_SPEED

#endif // __TARGET_HPP__
